[0m12:27:44.808841 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252634C08B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002526541F040>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252654530D0>]}


============================== 12:27:44.814838 | 6828ba48-655e-4311-9bea-02a19135b3d7 ==============================
[0m12:27:44.814838 [info ] [MainThread]: Running with dbt=1.8.7
[0m12:27:44.816080 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\vprya\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:27:50.773413 [debug] [MainThread]: Starter project path: c:\git\dbt\dbt-env\lib\site-packages\dbt\include\starter_project
[0m12:27:50.803865 [info ] [MainThread]: 
Your new dbt project "kafka_continuous_offsets_validate" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:27:50.804866 [info ] [MainThread]: Setting up your profile.
[0m12:27:50.806875 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m12:27:50.808871 [debug] [MainThread]: Command `dbt init` failed at 12:27:50.808871 after 6.05 seconds
[0m12:27:50.808871 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000252634C08B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025263353610>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000025263353490>]}
[0m12:27:50.809867 [debug] [MainThread]: Flushing usage events
